server:
  port: 8081

spring:
  rabbitmq:
    host: 192.168.152.100
    port: 5672
    username: guest
    password: guest
    
cicd:
  rabbitmq:
    exchange: simple_exchange
    queue: spring_boot_queue
    routingkey: routing_key